"""Weather condition code to description mapping."""

WEATHER_MAP = {
    1: "Selkeää",
    2: "Enimmäkseen selkeää",
    4: "Puolipilvistä",
    6: "Enimmäkseen pilvistä",
    7: "Pilvistä",
    9: "Sumua",
    71: "Yksittäisiä ukkoskuuroja",
    74: "Paikoin ukkoskuuroja",
    77: "Ukkoskuuroja",
    21: "Yksittäisiä sadekuuroja",
    24: "Paikoin sadekuuroja",
    14: "Sadekuuroja Jäätävää tihkua",
    17: "Jäätävää sadetta",
    11: "Tihkusadetta",
    31: "Puolipilvistä ja ajoittain heikkoa vesisadetta",
    34: "Enimmäkseen pilvistä ja ajoittain heikkoa vesisadetta",
    37: "Heikkoa vesisadetta",
    32: "Puolipilvistä ja ajoittain kohtalaista vesisadetta",
    35: "Enimmäkseen pilvistä ja ajoittain kohtalaista vesisadetta",
    38: "Kohtalaista vesisadetta",
    33: "Puolipilvistä ja ajoittain voimakasta vesisadetta",
    36: "Enimmäkseen pilvistä ja ajoittain voimakasta vesisadetta",
    39: "Voimakasta vesisadetta",
    41: "Puolipilvistä ja ajoittain heikkoa räntäsadetta tai räntäkuuroja",
    44: "Enimmäkseen pilvistä ja ajoittain heikkoa räntäsadetta tai räntäkuuroja",
    47: "Heikkoa räntäsadetta",
    42: "Puolipilvistä ja ajoittain kohtalaista räntäsadetta tai räntäkuuroja",
    45: "Enimmäkseen pilvistä ja ajoittain kohtalaista räntäsadetta tai räntäkuuroja",
    48: "Kohtalaista räntäsadetta",
    43: "Puolipilvistä ja ajoittain voimakasta räntäsadetta tai räntäkuuroja",
    46: "Enimmäkseen pilvistä ja ajoittain voimakasta räntäsadetta tai räntäkuuroja",
    49: "Voimakasta räntäsadetta",
    51: "Puolipilvistä ja ajoittain heikkoa lumisadetta tai lumikuuroja",
    54: "Enimmäkseen pilvistä ja ajoittain heikkoa lumisadetta tai lumikuuroja",
    57: "Heikkoa lumisadetta",
    52: "Puolipilvistä ja ajoittain kohtalaista lumisadetta tai lumikuuroja",
    55: "Enimmäkseen pilvistä ja ajoittain kohtalaista lumisadetta tai lumikuuroja",
    58: "Kohtalaista lumisadetta",
    53: "Puolipilvistä ja ajoittain sakeaa lumisadetta tai lumikuuroja",
    56: "Enimmäkseen pilvistä ja ajoittain sakeaa lumisadetta tai lumikuuroja",
    59: "Runsasta lumisadetta",
    61: "Yksittäisiä raekuuroja",
    64: "Paikoin raekuuroja",
    67: "Raekuuroja"
} 
